# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20.11_MVCAdvanced' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20.11_MVCAdvanced
	pod 'Alamofire'

  target '20.11_MVCAdvancedUITests' do
    # Pods for testing
  end

end
