# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '13.11_API-TVShows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 13.11_API-TVShows
	pod 'Alamofire'
	pod 'Kingfisher'

end
