# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '16.11_TvShows_MVController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 16.11_TvShows_MVController
	pod 'Alamofire'
	pod 'Kingfisher'
end
