# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '11.11_Network_CoinConversion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'

  # Pods for 11.11_Network_CoinConversion

end
