# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '04.11_CocoaPods_TestSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 04.11_CocoaPods_TestSample
pod 'Kingfisher', '~> 5.15'

end
